In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("C:/Users/sikan/Downloads/Log Regression and Clustering/Lab08/car selling dataset.csv")

In [5]:
data.head(5)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0

In [69]:
data.isnull().sum().sum()

0

In [70]:
data=data.dropna()

In [71]:
dummies=pd.get_dummies(data['name'])
dummies1=pd.get_dummies(data['fuel'])
dummies2=pd.get_dummies(data['owner'])
dummies3=pd.get_dummies(data['mileage'])

In [72]:
dummies.head(5)

,Ambassador CLASSIC 1500 DSL AC,Ambassador Classic 2000 DSZ AC PS,Ambassador Grand 1500 DSZ BSIII,Ambassador Grand 2000 DSZ PW CL,Ashok Leyland Stile LE,Audi A3 35 TDI Premium Plus,Audi A3 40 TFSI Premium,Audi A4 1.8 TFSI,Audi A4 2.0 TDI,Audi A4 2.0 TDI 177 Bhp Premium Plus,...,Volkswagen Vento Petrol Highline AT,Volkswagen Vento Petrol Trendline,Volvo S60 D4 SUMMUM,Volvo S90 D4 Inscription BSIV,Volvo V40 Cross Country D3,Volvo V40 D3 R-Design,Volvo XC40 D4 Inscription BSIV,Volvo XC40 D4 R-Design,Volvo XC60 Inscription D5 BSIV,Volvo XC90 T8 Excellence BSIV
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [73]:
merged=pd.concat([data,dummies,dummies1,dummies3],axis='columns')

In [74]:
merged.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,...,28.09 kmpl,28.4 kmpl,30.46 km/kg,32.26 km/kg,32.52 km/kg,33.0 km/kg,33.44 km/kg,42.0 kmpl,9.0 kmpl,9.5 kmpl
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,...,0,0,0,0,0,0,0,0,0,0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,...,0,0,0,0,0,0,0,0,0,0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,...,0,0,0,0,0,0,0,0,0,0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,...,0,0,0,0,0,0,0,0,0,0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,...,0,0,0,0,0,0,0,0,0,0

In [75]:
final=merged.drop(['name','seller_type','transmission','torque','fuel','mileage','owner','engine','max_power'],axis='columns')
final.head()

,year,selling_price,km_driven,seats,Ambassador CLASSIC 1500 DSL AC,Ambassador Classic 2000 DSZ AC PS,Ambassador Grand 1500 DSZ BSIII,Ambassador Grand 2000 DSZ PW CL,Ashok Leyland Stile LE,Audi A3 35 TDI Premium Plus,...,28.09 kmpl,28.4 kmpl,30.46 km/kg,32.26 km/kg,32.52 km/kg,33.0 km/kg,33.44 km/kg,42.0 kmpl,9.0 kmpl,9.5 kmpl
0,2014,450000,145500,5.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2014,370000,120000,5.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2006,158000,140000,5.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2010,225000,127000,5.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2007,130000,120000,5.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [76]:
Y=final['selling_price']
Y.head()

0    450000
1    370000
2    158000
3    225000
4    130000
Name: selling_price, dtype: int64

In [77]:
X=final.drop('selling_price',axis='columns')

In [83]:
from sklearn.model_selection import train_test_split

In [84]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)

In [85]:
from sklearn.linear_model import LinearRegression
model= LinearRegression()

In [86]:
model.fit(x_train,y_train)

LinearRegression()

In [101]:
y_prediction =  model.predict(x_test)
y_prediction

array([365705.39404297, 198649.19580078, 404807.23095703, ...,
       257901.99462891, 438358.12207031, 332145.73828125])

In [102]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
# predicting the accuracy score
score=r2_score(y_test,y_prediction)
print('r2 socre is ',score)
print('mean_sqrd_error is==',mean_squared_error(y_test,y_prediction))
print('root_mean_squared error of is==',np.sqrt(mean_squared_error(y_test,y_prediction)))

r2 socre is  -21404770728.0832
mean_sqrd_error is== 1.5226439729286713e+22
root_mean_squared error of is== 123395460732.09789

In [103]:
model.score(x_test,y_test)

-21404770728.0832